### PR TITLE
Features/upgrade to platform api

### PR DESCRIPTION
**Pull request by pixiitech**
Upgraded to heroku's platform api. Many thanks to plicjo! All rspec are passing, deploys have been tested.

### CODE REVIEW

**Comment by cmetro** [comment]
Thanks, @pixiitech! I just used your forked version to get a deployment out when I noticed that heroku removed the old API version. @mattpolito this worked well.

**Comment by mattpolito** [comment]
@cmetro Thanks for the verification. I'll take a look at getting this merged.

**Comment by mattpolito** [comment]
Thanks to @pixiitech @plicjo and all those involved on getting these changes in.

**Comment by plicjo** [comment]
Awesome!

**Pull request merged**
